// Stellar Gateway — main entry point.
//
// Startup sequence:
//  1. Load environment variables from .env (dev only)
//  2. Load AppConfig from env vars
//  3. Load SystemConfig from system.json
//  4. Initialise data store and repositories
//  5. Initialise services (auth, voyage, booking, proxy)
//  6. Initialise handlers
//  7. Register routes with middleware
//  8. Start HTTP server
//
// All application configuration is injected at startup — no package reads
// env vars or opens files after main() returns.

//	@title			Stellar Gateway API
//	@version		1.0
//	@description	The Stellar Gateway is the single entry point for all frontend requests. It handles authentication, voyage search, booking management, and proxies to the AI, vision, and routing microservices.
//	@termsOfService	http://localhost:8080

//	@contact.name	Stellar Dev
//	@contact.url	http://localhost:8080

//	@license.name	MIT

//	@host		localhost:8080
//	@BasePath	/api

//	@securityDefinitions.apikey	BearerAuth
//	@in							header
//	@name						Authorization
//	@description				JWT Bearer token. Format: "Bearer <token>"

package main

import (
	"fmt"
	"log/slog"
	"net/http"
	"os"
	"strings"

	"github.com/go-chi/chi/v5"
	chiMiddleware "github.com/go-chi/chi/v5/middleware"
	httpSwagger "github.com/swaggo/http-swagger/v2"

	"github.com/stellar/gateway/config"
	"github.com/stellar/gateway/data"
	"github.com/stellar/gateway/handlers"
	appMiddleware "github.com/stellar/gateway/middleware"
	"github.com/stellar/gateway/repository"
	"github.com/stellar/gateway/services"

	_ "github.com/stellar/gateway/docs" // Generated by swag init — do not remove
)

func main() {
	// -----------------------------------------------------------------
	// 1. Load .env in development (best-effort — no error if absent)
	// -----------------------------------------------------------------
	loadDotEnv()

	// -----------------------------------------------------------------
	// 2. App config from environment variables
	// -----------------------------------------------------------------
	appCfg, err := config.Load()
	if err != nil {
		slog.Error("failed to load app config", "error", err)
		os.Exit(1)
	}

	// -----------------------------------------------------------------
	// 3. System config from system.json
	// -----------------------------------------------------------------
	sysCfg, err := config.LoadSystemConfig(appCfg.SystemConfigPath)
	if err != nil {
		slog.Error("failed to load system config", "error", err, "path", appCfg.SystemConfigPath)
		os.Exit(1)
	}
	slog.Info("system config loaded",
		"bodies", len(sysCfg.Bodies),
		"routes", len(sysCfg.Routes),
		"shipClasses", len(sysCfg.ShipClasses),
	)

	// -----------------------------------------------------------------
	// 4. Data store and repositories
	// -----------------------------------------------------------------
	store := data.NewStore(appCfg.DataPath)
	userRepo := repository.NewUserRepository(store)
	bookingRepo := repository.NewBookingRepository(store)

	// -----------------------------------------------------------------
	// 5. Services
	// -----------------------------------------------------------------
	authService := services.NewAuthService(userRepo, appCfg)
	voyageService := services.NewVoyageService(sysCfg)
	bookingService := services.NewBookingService(bookingRepo, userRepo, voyageService, sysCfg)
	proxyService := services.NewProxyService(appCfg.AIServiceURL, appCfg.VisionServiceURL, appCfg.RoutingServiceURL)

	// -----------------------------------------------------------------
	// 6. Handlers
	// -----------------------------------------------------------------
	authHandler := handlers.NewAuthHandler(authService)
	systemHandler := handlers.NewSystemHandler(sysCfg)
	voyageHandler := handlers.NewVoyageHandler(voyageService)
	scheduleHandler := handlers.NewScheduleHandler(voyageService)
	bookingHandler := handlers.NewBookingHandler(bookingService)
	proxyHandler := handlers.NewProxyHandler(proxyService)

	// -----------------------------------------------------------------
	// 7. Router and middleware
	// -----------------------------------------------------------------
	r := chi.NewRouter()

	// Global middleware
	r.Use(chiMiddleware.Recoverer)
	r.Use(appMiddleware.Logger)
	r.Use(appMiddleware.CORS(appCfg.AllowedOrigins))

	// Swagger UI — available at /swagger/index.html
	// Run `swag init` from the gateway/ directory to regenerate docs/
	r.Get("/swagger/*", httpSwagger.Handler(
		httpSwagger.URL("/swagger/doc.json"),
	))

	// Health check
	r.Get("/health", func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		w.Write([]byte(`{"status":"ok","service":"stellar-gateway"}`))
	})

	// -----------------------------------------------------------------
	// API routes under /api
	// -----------------------------------------------------------------
	r.Route("/api", func(r chi.Router) {

		// Auth — public
		r.Route("/auth", func(r chi.Router) {
			r.Post("/register", authHandler.Register)
			r.Post("/login", authHandler.Login)
			r.Post("/refresh", authHandler.Refresh)
			// Auth-protected auth routes
			r.Group(func(r chi.Router) {
				r.Use(appMiddleware.Authenticate(authService))
				r.Get("/me", authHandler.GetMe)
				r.Post("/face-vector", authHandler.UpdateFaceVector)
			})
		})

		// System — public, no auth required
		r.Route("/system", func(r chi.Router) {
			r.Get("/bodies", systemHandler.GetBodies)
			r.Get("/routes", systemHandler.GetRoutes)
			r.Get("/ships", systemHandler.GetShips)
			r.Get("/spaceports", systemHandler.GetSpaceports)
			r.Get("/cabin-classes", systemHandler.GetCabinClasses)
			r.Get("/cryo-options", systemHandler.GetCryoOptions)
			r.Get("/add-ons", systemHandler.GetAddOns)
			r.Get("/loyalty-tiers", systemHandler.GetLoyaltyTiers)
			r.Get("/pricing", systemHandler.GetPricing)
		})

		// Voyages — public
		r.Route("/voyages", func(r chi.Router) {
			r.Get("/search", voyageHandler.Search)
			r.Get("/orbital-positions", voyageHandler.GetOrbitalPositions)
			r.Get("/closest-approach", voyageHandler.GetClosestApproach)
			r.Post("/price", voyageHandler.CalculatePrice)
			r.Get("/{id}", voyageHandler.GetVoyage)
		})

		// Schedule — public
		r.Route("/schedule", func(r chi.Router) {
			r.Get("/{routeId}", scheduleHandler.GetSchedule)
		})

		// Bookings — auth required
		r.Route("/bookings", func(r chi.Router) {
			r.Use(appMiddleware.Authenticate(authService))
			r.Post("/", bookingHandler.CreateBooking)
			r.Get("/me", bookingHandler.GetUserBookings)
			r.Get("/{id}", bookingHandler.GetBooking)
			r.Patch("/{id}/cancel", bookingHandler.CancelBooking)
		})

		// Proxy — microservices
		r.Route("/chat", func(r chi.Router) {
			r.Use(appMiddleware.Authenticate(authService))
			r.Post("/", proxyHandler.Chat)
		})

		r.Route("/vision", func(r chi.Router) {
			// Face authentication is public (no existing JWT yet — that's the point)
			r.Post("/authenticate", proxyHandler.AuthenticateFace)
			// Enrolment requires an existing authenticated session
			r.Group(func(r chi.Router) {
				r.Use(appMiddleware.Authenticate(authService))
				r.Post("/enrol", proxyHandler.EnrolFaceVector)
			})
		})

		r.Route("/routing", func(r chi.Router) {
			r.Use(appMiddleware.Authenticate(authService))
			r.Post("/optimise", proxyHandler.OptimiseRoute)
		})
	})

	// -----------------------------------------------------------------
	// 8. Start server
	// -----------------------------------------------------------------
	addr := fmt.Sprintf(":%s", appCfg.Port)
	slog.Info("stellar gateway starting",
		"addr", addr,
		"env", appCfg.Env,
		"swagger", fmt.Sprintf("http://localhost:%s/swagger/index.html", appCfg.Port),
	)

	if err := http.ListenAndServe(addr, r); err != nil {
		slog.Error("server error", "error", err)
		os.Exit(1)
	}
}

// loadDotEnv reads a .env file from the current directory and sets env vars.
// It is intentionally simple — no external dependency required.
// Only runs if a .env file exists; silently skips if absent.
func loadDotEnv() {
	f, err := os.Open(".env")
	if err != nil {
		return // .env is optional
	}
	defer f.Close()

	var lines []string
	buf := make([]byte, 0, 4096)
	tmp := make([]byte, 1)
	line := ""

	for {
		n, err := f.Read(tmp)
		if n > 0 {
			ch := string(tmp[:n])
			if ch == "\n" {
				lines = append(lines, strings.TrimRight(line, "\r"))
				line = ""
			} else {
				line += ch
			}
		}
		if err != nil {
			if line != "" {
				lines = append(lines, line)
			}
			break
		}
	}
	_ = buf

	for _, l := range lines {
		// Strip comments and blank lines
		if len(l) == 0 || l[0] == '#' {
			continue
		}
		for i, ch := range l {
			if ch == '=' {
				key := l[:i]
				val := l[i+1:]
				// Only set if not already set — env vars take precedence over .env
				if _, exists := os.LookupEnv(key); !exists {
					os.Setenv(key, val)
				}
				break
			}
		}
	}
}